"""Agregar password_hash

Revision ID: 78cf2517e455
Revises: 4b318a9ebb0b
Create Date: 2023-11-08 02:23:15.241233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78cf2517e455'
down_revision = '4b318a9ebb0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.alter_column('texto_comentario',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('fecha_creacion',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clave_hash', sa.String(length=100), nullable=False))
        batch_op.drop_column('clave')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clave', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('clave_hash')

    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.String(length=100),
               type_=mysql.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('texto_comentario',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
