"""Arreglar fecha_creacion

Revision ID: bb8eec847633
Revises: 78cf2517e455
Create Date: 2023-11-08 15:06:49.900677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb8eec847633'
down_revision = '78cf2517e455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.alter_column('texto_comentario',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('fecha_creacion',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('texto_comentario',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
